#!/bin/sh

rm -f "$HOME/var/cache/man."*
IFS=", "
apropos . | while read -r manp
do
	desc="${manp##*") - "}"
	manp="${manp%%) - *}"
	sect="${manp##*"("}"
	manp="${manp%%"("*}"
	case "$sect" in
	(*[!0-9]*) continue ;;
	esac
	for i in $manp
	do
		echo "$i	$desc" >> "$HOME/var/cache/man.$sect"
	done
done
for file in "$HOME/var/cache/man."*
do
	awk -F "\t" '
		{
			gsub(/[][{}_-]/, "\\\\&")
			printf "%s [%s]\n", $1, $2
		}
	' "$file" | sponge "$file"
done
