#!/bin/sh
# open surf (in a new tab, if possible)

{
	xprop -root -notype ' $0+\n' _NET_CLIENT_LIST_STACKING |\
	grep -oEe '0x[0-9A-Fa-f]+'
} | {
	surfid=""
	while read -r winid
	do
		if test "$(xprop -id "$winid" -notype ' $1' WM_CLASS | cut -d' ' -f2-)" = '"Surf"'
		then
			surfid="$winid"
		fi
	done
	if test -n "$surfid"
	then
		exec surf -e "$surfid" "$@" &
	else
		exec surf "$@" &
	fi
}
