#!/bin/sh
#
# NAME
#       xfiles-menu - context menu for xfiles
#
# SYNOPSOS
#       xfiles-menu
#       xfiles-menu file...
#
# DESCRIPTION
#       In the first form (without argument), this command opens a menu
#       targeting the current working directory.  In the second form,
#       this command opens a menu targeting the files in the current
#       working directory given as arguments.
#
#       The directory menu has the following entries:
#
#       - copy:
#         Copy the snarfed files into the current directory.  It first
#         opens a terminal window asking permission for the copying to
#         occur.  If the user enters "Y", the snarfed files are copied
#         into the current directory.  This action depends on xsel(1).
#
#       - move:
#         Move the snarfed files into the current directory.  It first
#         opens a terminal window asking permission for the moving to
#         occur.  If the user enters "Y", the snarfed files are moved
#         into the current directory.  This action depends on xsel(1).
#
#       The files menu has the following entries:
#
#       - rename:
#         Open a terminal window with the editor for renaming the files
#         given as arguments.  This action depends on bulkrename(1).
#
#       - snarf:
#         Snarf the files given as arguments to copy or move later.
#         This action depends on xsel(1).
#
#       - trash:
#         Send files given as arguments to the trash WITHOUT ASKING FOR
#         PERMISSION (this is not a problem, since the trash command is
#         expected to just move the file to a trash, not delete it).
#
#       - edit:
#         Edit the first file given as argument.
#         This action depends on plumb(1).
#
#       xfiles-menu was wrote to be called by xfiles(1).
#
# DEPENDENCIES
#
#       xfiles-menu requires the following dependencies:
#
#       - xsel:
#         (http://www.vergenet.net/~conrad/software/xsel).
#         Manipulate the X Selection.
#
#       - bulkrename:
#         (https://github.com/phillbush/fmutils/blob/master/bulkrename)
#         Edit file names in vi(1) or other editor.
#
#       - trash:
#         (https://github.com/phillbush/fmutils/blob/master/trash)
#         Send files to the trash.
#
#       - plumb:
#         (https://github.com/phillbush/plumb)
#         Invoke actions (such as "open" or "edit") on a file.
#
# ENVIRONMENT
#       The following environment variables affect the execution of
#       xfiles-menu.
#
#       DISPLAY
#               The display to pop up the menus.
#
#       MENUCMD
#               The command to pop up the menu (can be xmenu or pmenu).
#
#       TERMCMD
#               The command to open a terminal (defaults to xterm).
#
# SEE ALSO
#       xfiles(1).
#
# BUGS
#       The word "snarf" means basically "save to the clipboard".

MENUCMD="${MENUCMD:-"pmenu"}"
TERMCMD="${TERMCMD:-"xterm"}"

term() {
	"$TERMCMD" -e "$@"
}

paste() {
	term /bin/sh -c '{
		xsel -ob
		echo
	} | {
		set --
		while read f
		do
			case "$f" in
			("")
				;;
			(*)
				printf "\t%s\n" "$f"
				set -- "$@" "$f"
				;;
			esac
		done
		printf "copy? [y/N] "
		read arg </dev/tty
		case "$arg" in
		([Yy]*)
			'"$1"' "$@" .
			;;
		esac
	}'
}

dirmenu() {
	case "$(
	"$MENUCMD" <<-EOF
		copy
		move
	EOF
	)" in
	("copy")
		paste cp
		;;
	("move")
		paste mv
		;;
	esac
}

filemenu() {
	case "$(
	"$MENUCMD" <<-EOF
		rename
		snarf
		trash
		edit
	EOF
	)" in
	("rename")
		term bulkrename "$@"
		;;
	("snarf")
		xsel -op | xsel -ib &
		;;
	("trash")
		trash "$@"
		;;
	("edit")
		plumb -e -- "$1"
		;;
	esac
}

case "$#" in
(0)
	dirmenu "$@"
	;;
(*)
	filemenu "$@"
	;;
esac
exit
