.TH HOME 7
.SH NAME
home \- layout of home filesystem
.SH DESCRIPTION
The contents of my
.B $HOME
are listed below.
Note that I do not use the XDG home structure.
.TP
.B ~/.profile
Shell script that sets the environment variables necessary to set up a user session.
.TP
.B ~/.session
Shell script called by ksh(1) to set up a shell session (prompt, aliases, etc).
.TP
.B ~/.xsession
Shell script called by xenodm(1) to set up a X session (notification system, window manager, etc).
.TP
.B ~/apps/
Contains .desktop files for applications that should be listed by pmenu(1).
.TP
.B ~/files/
Where I archive documents, media, and files for consumption.
Each category of files has a subdirectory in it.
For example,
.B ~/files/doc/
for non-fiction books;
.B ~/files/lit/
for fiction books;
.B ~/files/meme/
is the meme folder;
.B ~/files/mus/
is the music folder;
etc.
.TP
.B ~/proj/
Where I put whatever I am working on (mostly college stuff, things I am learning, and programs I maintain).
Each project has a subdirectory in it.
For example,
.B ~/proj/xmenu/
for xmenu(1);
.B ~/proj/c/
for notes on the C Programming Language;
etc.
.TP
.B ~/rules/
Configuration files (aka dotfiles).
For example
.B ~/rules/vimrc
(for vim);
.B ~/rules/keybindings
(for sxhkd);
etc.
.TP
.B ~/skel/
Skeleton files, that is, templates for different file formats.
For example, 
.B ~/skel/Makefile
is a template for a Makefile;
.B ~/skel/man.1
is a template for a section 1 man page;
etc.
.TP
.B ~/theme/
Where I keep icons, cursors, fonts, etc.
.TP
.B ~/tmp/
Download directory and where I dump stuff.
I try to keep it clean, but most of the time it is a mess.
.TP
.B ~/usr/
Program files (binaries, sources, manuals, etc).
Each subdirectory contain files installed from a given source or using a given method.
For example,
.B ~/usr/local/
contains data for programs I install manually;
.B ~/usr/python/
is for programs installed with pip(1);
.B ~/usr/go/
is for programs installed with go(1);
etc.
Each subdirectory contains the directories
.BR bin/ ,
.BR src/ ,
.BR man/ ,
and
.B etc/
(for binaries, source, manual and other files).
For example.
.B ~/usr/go/bin/lf
is the binary for lf installed by go(1);
.B ~/usr/local/man/man1/xmenu.1
is the manual for xmenu(1) installed by its Makefile;
etc.
.TP
.B ~/var/
Files that are not managed manually, but by applications.
For example,
.B ~/var/trash/
for trashed files managed by trash(1) and untrash(1);
.B ~/var/mail/
for email managed by mutt(1), mbsync(1) and others;
.B ~/var/history
for command history from ksh(1), xprompt(1) and others;
.B ~/var/cache
for cache used and generated by several programs.
.SH SEE ALSO
.IR desk (7),
.IR hier (7)
