#!/bin/sh
sys="$(uname)"
wm="$(xprop -id `xprop -root _NET_SUPPORTING_WM_CHECK | cut -d' ' -f 5` _NET_WM_NAME | sed 's/^_NET_WM_NAME[^"]*"//;s/".*//')"
shell="$(basename $SHELL)"
pkgs="$(ls /var/db/pkg | wc -l | tr -d ' ')"
host="$(sysctl -n hw.version)"
color1="[30m[40m   [31m[41m   [32m[42m   [33m[43m   [34m[44m   [35m[45m   [36m[46m   [37m[47m   [m"
color2="[38;5;8m[48;5;8m   [38;5;9m[48;5;9m   [38;5;10m[48;5;10m   [38;5;11m[48;5;11m   [38;5;12m[48;5;12m   [38;5;13m[48;5;13m   [38;5;14m[48;5;14m   [38;5;15m[48;5;15m   [m"

cat <<EOF

⎧ [1msystem:[m $sys   [30Gillegal1 = 0Oo                ⎫
⎪     [1mwm:[m $wm    [30GABCDEFGHIJKLMNOPQRSTUVWXYZ    ⎪
⎨  [1mshell:[m $shell [30Gabcdefghijklmnopqrstuvwxyz    ⎬
⎪   [1mpkgs:[m $pkgs  [30G0123456789 () {} [] <> @ $    ⎪
⎩   [1mhost:[m $host  [30G~ # % ^ & * - = + / ? : ; _ | ⎭

[18G$color1
[18G$color2

EOF
