.TH PROG 1
.SH NAME
prog \- lorem ipsum dolor sit amet
.SH SYNOPSIS
.B prog
.RB [ \-n ]
.RB [ \-f
.IR file ]
.IR arg ...
.SH DESCRIPTION
.B prog
consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
.PP
The options are as follows:
.TP
.B \-n
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Curabitur pretium tincidunt lacus.
Nulla gravida orci a odio.
Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.
Integer in mauris eu nibh euismod gravida.
Duis ac tellus et risus vulputate vehicula.
Donec lobortis risus a elit.
Etiam tempor.
.TP
.BI \-f " file"
Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam.
Maecenas fermentum consequat mi.
Donec fermentum.
Pellentesque malesuada nulla a mi.
Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.
.SH ENVIRONMENT
The following environment variables affect the execution of
.B prog
.TP
.B PATH
Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam.
Maecenas fermentum consequat mi.
Donec fermentum.
Pellentesque malesuada nulla a mi.
Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.
.SH FILES
.TP
.B /path/to/file
Maecenas fermentum consequat mi.
Donec fermentum.
Pellentesque malesuada nulla a mi.
Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH EXAMPLES
Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat:
.IP
.EX
$ prog
.EE
.PP
Cras mollis scelerisque nunc.
Nullam arcu.
Aliquam consequat:
.IP
.EX
$ prog -n
.EE
.PP
Curabitur augue lorem, dapibus quis, laoreet et, pretium ac, nisi:
.IP
.EX
$ prog -f sample.txt
.EE
.SH SEE ALSO
.IR true (1),
.IR false (1)
.PP
Brian W. Kernighan, and Denis M. Ritchie,
.I The C Programming Language,
Prentice Hall,
1988.
ISBN 0-13-110362-8
.SH HISTORY
An
.B prog
utility appeared somewhere. 
.SH BUGS
Yes.
