#!/bin/ksh
#
# Usage: . ~/.kshrc
# Initialization script for interactive ksh(1) sessions.
# Depends only on OpenBSD base utilities.
#
# © 2024 Lucas de Sena <lucas at seninha dot org>.
# No rights reserved.  Dedicated into Public Domain.  Use as you will.
# THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY (works on my machine™)

. /etc/ksh.kshrc
. "$HOME/.profile"

# run given command on background
run() (
	trap : HUP
	exec 1>/dev/null 2>/dev/null 0</dev/null
	exec "$@" &
)

# run given command with doas; or re-run previous command with doas(1)
fuck() {
	test "$#" -gt 0 && {
		doas -- "$@" 
		return
	}
	typeset n="$(
		fc -l 1 |
		sed -En '
			/^[[:digit:]]+[[:space:]]+fuck/!h
			${
				g
				s/[[:space:]].*//
				p
			}
		'
	)"
	if test -z "$n"
	then
		echo "ksh: fuck: no command to retry" >&2
		return 127
	fi
	fc -e "sed -i '/^doas/!s/^/doas /'" "$n"
}

# extend cd with two forms for going up; and set completions for make(1)
cd() {
	case "$#" in
	(0) set -- "$HOME" ;;
	(1)                ;;
	(*) set -- "$*"    ;;
	esac
	case "$1" in
	(.+(.)?(/*))
		# go up this much dots, then to PATH:   cd ..../foo/bar
		set -- "$1" "$PWD"
		while true
		do
			case "$1" in
			(..*) set -- "${1#.}" "${2%/*}" ;;
			(*)   break                     ;;
			esac
		done
		set -- "$2/${1#*/}"
		;;
	(..*)
		# go up to first directory with NAME:   cd ..NAME
		set -- "${PWD%"${PWD##*"${1#".."}"}"}"
		;;
	esac
	command cd "$1" >/dev/null || return 1
	set -A complete_make -- $(
		exec 2>/dev/null
		make -qp |
		sed -n '/^[A-Za-z][^ :]* *:/{s/\([^: ]*\).*/\1/p;}'
	)
	case "$PWD/" in
	("$HOME"/*)
		printf "%s\n" "~${PWD#"${HOME}"}"
		;;
	(*)
		printf "%s\n" "$PWD"
		;;
	esac
	return 0
}

# read stdin into temp file; run args on file; write file to stdout
pee() {
	test "$#" -eq 0 && set -- cat
	typeset tmp="$(mktemp)"
	test -n "$tmp" && test -w "$tmp" && test -r "$tmp" || {
		rm "$tmp" 2>/dev/null
		return 1
	}
	cat >"$tmp" && "$@" "$tmp" <>/dev/tty >&0 2>&0 && cat "$tmp"
	rm "$tmp" 2>/dev/null
}

# check if command exists and, if so, set its completable arguments
complete() {
	typeset cmd="$1"
	shift
	command -v "$cmd" >/dev/null || return
	case "$1" in
	([1-9])
		typeset arg="_$1"
		shift
		;;
	(*)
		typeset arg=""
		shift
		;;
	esac
	set -A complete_"${cmd}${arg}" -- "$@"
}

{
	complete sysctl $(sysctl | sed 's,[= ].*,,')
	complete rcctl 1 disable enable get ls order set restart start stop
	complete rcctl 2 $(rcctl ls all)
	complete vmd 1 console load reload start stop reset status send receive
	complete vmd $(vmctl status | awk '!/NAME/{print $NF}')
	complete got 1 add backout blame branch cat checkout cherrypick \
	clone commit diff fetch histedit import info init integrate log \
	merge patch rebase ref remove revert send stage status tag tree \
	unstage update
} 2>/dev/null

# force emacs[1] keybindings even when $VISUAL is set to a vi-like editor
# [1]: That's actually UNIX keybindings; see <https://unix-kb.cat-v.org>.
set -o emacs
set -o braceexpand
bind '^H'=delete-word-backward

# history
FCEDIT="${VISUAL:-${EDITOR:-"vi"}}"
HISTFILE="$HOME/var/history/ksh.hist"
HISTSIZE=10000
HISTCONTROL="ignoredups:ignorespace"
alias history="fc -l 1"
alias redo="fc -e :"

# file management (be verbose and interactive)
alias rm='rm -vi'
alias mv='mv -vi'
alias cp='cp -viR'
alias mkdir='mkdir -p'

# binary file dump
alias hex='hexdump -C'
alias od='od -cAx'

# human-readable sizes
alias df='df -h'
alias du='du -hc'

# lazyman aliases
alias ls='ls -1Fh'
alias lc='ls -C'
alias ll='ls -l'
alias calc='bc -l'

# commands with command as argument (for futher alias expension)
alias xargs='tr "\n" "\0" | xargs -0 '
alias doas='doas '
alias fuck='fuck '
alias timeout='timeout '
alias apply='apply '

# case
alias grep='egrep'
alias fgrep='fgrep -i'

# pipeline utils
# PROTIP: Running "doas foo >/root/file" does not write into /root/file.
#         If that's what you want; use "foo | doas save secret" instead.
# PROTIP: Use "doas cat secret | foo" rather than "doas foo secret" for
#         priviledge separation (useless cat is not useless).
# PROTIP: Use "foo | see | bar" to see what is going on in the pipeline.
# PROTIP: Avoid redirection operators (<, >, >>) on interactive shells!
alias overwrite='save -f --'
alias append='save -a --'
alias saveas='save -b --'
alias see='tee /dev/tty'
alias vee='pee "${EDITOR:-"${VISUAL:-"vi"}"}" --'
alias lee='pee "${PAGER:-"less"}" --'

# typos
alias mkae='make'
alias makemake='make'

# prompt is "\n HOST ❯ " (red if root; HOST if ssh; also set window title)
PS1='$(
	case "$(id -u)" in
		(0) color="1;31m" ;;
		(*) color="1m"    ;;
	esac
	case "$PWD/" in
		("$HOME"/*) cwd="~${PWD#"${HOME}"}" ;;
		(*)         cwd="$PWD"              ;;
	esac
	term='"$(tty | sed s,^/dev/,,)"'
	host='"${SSH_CONNECTION:+"$(hostname)"}"'
	title="$host${host:+:}$cwd - $term"
	printf "\e[0m\e]0;%s\a\n%s \e[%s❯ \e[0m" "$title" "$host" "$color"
)'

# 2nd prompt is " ❮ " (red if root, white otherwise)
PS2="$(
	case "$(id -u)" in
		(0) color="1;31m" ;;
		(*) color="1m"    ;;
	esac
	printf "\e[0m \e[%s❮ \e[0m" "$color"
)"

# print last command's exit status, if non-zero
trap 'printf "\e[1;31mEXIT: %s\e[0m\n" "$?"' ERR

# run cd function above just to set completion for make(1)
cd . >/dev/null 2>&1

export GPG_TTY="$(tty)"
