#!/bin/sh

# necessary for X 21.1.1
xrandr --dpi 96

# Load environment variables and xresources
. $HOME/.profile
expenv $RULESDIR/Xresources | xrdb -merge -load -

# Load keymap
xkbcomp $RULESDIR/xkeymap $DISPLAY 2>/dev/null

# fonts
xset +fp $HOME/lib/fonts
xset fp rehash

# make mouse invisible after a brief period
unclutter &

# thinkpad trackpoint
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5
synclient TapButton1=1
synclient TapButton2=2
synclient TapButton3=3
synclient AccelFactor=0
synclient HorizTwoFingerScroll=1

# Set background
feh --no-fehbg --bg-tile "$RULESDIR/wallpaper.png"

# compositor
picom -c -l -15 -t -15 \
      --shadow-radius 15 \
      --shadow-green 1.0 \
      --shadow-blue 1.0 \
      --use-ewmh-active-win \
      --shadow-exclude '!focused' &

# music daemon
mpd

# window manager
shod - <<-EOF
	# menu system
	ctrlmenu $RULESDIR/control &
	pmenu -ex 4-3 <$RULESDIR/rootmenu &

	# dockapps
	paginator -iw -g64x192 -l1x5 &
	taskinator -vihw &
	bubblemon &
	wmapm &
	wmclock &
	wmpdart &
EOF
